############# English navigation ##############

# main menu
[[main]]
name = "Início"
url = ""
weight = 1

[[main]]
name = "Sobre"
url = "about/"
weight = 2

[[main]]
name = "Contato"
url = "contact/"
weight = 3

# footer menu
[[footer]]
name = "Início"
url = "/"
weight = 1

[[footer]]
name = "Sobre"
url = "about/"
weight = 2

[[footer]]
name = "Contato"
url = "contact/"
weight = 3
