about_widget_content = "Estudante de ensino médio, programador, atleta e futuro engenheiro da Força Aérea Brasileira"
address = "Sorriso, Mato Grosso, Brasil"
author = "Themefisher"
contact_form_action = "https://formspree.io/f/xeqneowy"
copyright = "Feito com ❤️ e ☕ por João Flávio"
custom_script = ""
description = "Bem vindo ao meu espaço na internet. Blog, portfólio, etc."
email = "joaoflaviopinto@protonmail.com"
favicon = "images/favicon.png"
featured_post_title = "Posts em destaque"
footer_content = "\"Certamente, o nobre Engenheiro tem no peito a fibra varonil. É vibrante, veraz e, altaneiro. Segue honrado, de pé pelo Brasil!\""
image = "images/logo.png"
logo = "images/logo.png"
logo_text = "Boilerplate"
logo_width = "150x"
mainSections = ["blog"]
mobile = "+55 (66) 97400-2072"
navbar_fixed = false
recent_post_title = "Posts recentes"
search = true
[advertisement]
image = "images/promotion.png"
link = "https://discord.gg/bYTyadn3u8"
[banner]
background_image = "/images/banner-bg-shape.svg"
button_label = "Saiba mais sobre mim"
button_link = "about/"
content = "Aqui eu posto sobre minha vida pessoal, acadêmica e profissional"
enable = true
image = "images/banner.png"
title_large = "Bem vindo **!**"
title_small = "ao meu blog pessoal"
[cookies]
button = "I Accept"
content = "This site uses cookies. By continuing to use this website, you agree to their use."
enable = false
expire_days = 2
[preloader]
enable = false
preloader = ""
[subscription]
enable = true
mailchimp_form_action = "https://interm.us20.list-manage.com/subscribe/post?u=458b5aec1c4243e39e1664e4f&amp;id=a6259aa8fca6259aa8fc"
mailchimp_form_name = "b_458b5aec1c4243e39e1664e4f_a6259aa8fc"
[widgets]
sidebar = ["about", "categories", "recent-post"]
[[social]]
icon = "fab fa-instagram"
link = "https://www.instagram.com/joflaviop/"
title = "instagram"
[[social]]
icon = "fab fa-github"
link = "https://github.com/joao-flavio"
title = "github"
[[social]]
icon = "fab fa-linkedin"
link = "https://linkedin.com/in/joao-flavio"
title = "linkedin"
